#!bin/python
import socket
import sys

def checkIP():
  hostname = socket.gethostname()
  ip = socket.gethostbyname(hostname)
  print(f"ip: {ip}")

def checkHostname():
  hostname = socket.gethostname()
  print(f"hostname: {hostname}")

def createServer():
  socket.create_server(sys.argv[2])

def setHostname():
  socket.sethostname(sys.argv[2])

def connect():
  socket.connect(sys.argv[2])

if sys.argv[1] == "ip":
  checkIP()
elif sys.argv[1] == "hostname":
  checkHostname()
elif sys.argv[1] == "create-server":
  createServer()
elif sys.argv[1] == "set-hostname":
  setHostname()
elif sys.argv[1] == "connect":
  connect()
else:
  print("""Valid Commands:
  nettool ip
  nettool hostname
  netttool set-hostname
  nettool create-server <address>
  nettool connect <address>
  """)