#!bin/python
import socket
import sys

def checkIP():
  ip = socket.gethostbyname(hostname)
  print(f"ip: {ip}")

def checkHostname():
  hostname = socket.gethostname()
  print(f"hostname: {hostname}")


if sys.argv[1] == "ip":
  checkIP()
if sys.argv[1] == "info":
  checkInfo()